version: '3'

services:
  python:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - chrome
    environment:
      - fooda_email=${fooda_email}
      - fooda_password=${fooda_password}
      - selenium_host=chrome
    ports:
      - "5000:5000"
  chrome:
    image: selenium/standalone-chrome-debug
    ports:
      - "4444:4444"
      - "5900:5900"
