version: '3'

services:
  python:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - chrome
    environment:
      - fooda_email=${fooda_email}
      - fooda_password=${fooda_password}
      - selenium_host=chrome
    ports:
      - "5021:5000"
  chrome:
    image: selenium/standalone-chrome
    healthcheck:
      test: wget -qO - http://chrome:4444/wd/hub || exit 1
      interval: 3s
      timeout: 3s
      retries: 2
